@isTest
private class nissanoneToOneNnanetComCallcentre_Test {
    
private static nissanoneToOneNnanetComCallcentre obj = new nissanoneToOneNnanetComCallcentre();
private static nissanoneToOneNnanetComCallcentre.GetVersion_element obj1 = new nissanoneToOneNnanetComCallcentre.GetVersion_element();
private static nissanoneToOneNnanetComCallcentre.SearchCustomer_element obj2 = new nissanoneToOneNnanetComCallcentre.SearchCustomer_element();
private static nissanoneToOneNnanetComCallcentre.CallResolution_element  obj3 = new nissanoneToOneNnanetComCallcentre.CallResolution_element();
private static nissanoneToOneNnanetComCallcentre.GetAppointmentSubscribeURL_element  obj4 = new nissanoneToOneNnanetComCallcentre.GetAppointmentSubscribeURL_element ();
private static nissanoneToOneNnanetComCallcentre.GetServicesDueResponse_element  obj5 = new nissanoneToOneNnanetComCallcentre.GetServicesDueResponse_element ();
private static nissanoneToOneNnanetComCallcentre.CheckAppointmentTime_element obj6 = new nissanoneToOneNnanetComCallcentre.CheckAppointmentTime_element();
private static nissanoneToOneNnanetComCallcentre.CallCentreSoap  obj7 = new nissanoneToOneNnanetComCallcentre.CallCentreSoap(); 
private static nissanoneToOneNnanetComCallcentre.CheckAppointmentResponse_element  obj8 = new nissanoneToOneNnanetComCallcentre.CheckAppointmentResponse_element();
private static nissanoneToOneNnanetComCallcentre.Ping_element  obj9 = new nissanoneToOneNnanetComCallcentre.Ping_element();
private static nissanoneToOneNnanetComCallcentre.CheckAppointmentTimeResponse_element   obj10 = new nissanoneToOneNnanetComCallcentre.CheckAppointmentTimeResponse_element();
private static nissanoneToOneNnanetComCallcentre.GetPrimaryContactInfo_element   obj11 = new nissanoneToOneNnanetComCallcentre.GetPrimaryContactInfo_element();
private static nissanoneToOneNnanetComCallcentre.CheckAppointment_element   obj12 = new nissanoneToOneNnanetComCallcentre.CheckAppointment_element();
private static nissanoneToOneNnanetComCallcentre.GetAssociatedCustomers_element  obj13 = new nissanoneToOneNnanetComCallcentre.GetAssociatedCustomers_element();
private static nissanoneToOneNnanetComCallcentre.GetSecurityToken_element  obj14 = new nissanoneToOneNnanetComCallcentre.GetSecurityToken_element();
private static nissanoneToOneNnanetComCallcentre.GetCommunicationHistory_element  obj15 = new nissanoneToOneNnanetComCallcentre.GetCommunicationHistory_element();
private static nissanoneToOneNnanetComCallcentre.SearchCustomerResponse_element  obj16 = new nissanoneToOneNnanetComCallcentre.SearchCustomerResponse_element();
private static nissanoneToOneNnanetComCallcentre.GetLog_element  obj17 = new nissanoneToOneNnanetComCallcentre.GetLog_element();
private static nissanoneToOneNnanetComCallcentre.GetAssociatedCustomersResponse_element  obj18 = new nissanoneToOneNnanetComCallcentre.GetAssociatedCustomersResponse_element();
private static nissanoneToOneNnanetComCallcentre.GetLogResponse_element  obj19 = new nissanoneToOneNnanetComCallcentre.GetLogResponse_element();
private static nissanoneToOneNnanetComCallcentre.GetPrimaryContactInfoResponse_element   obj20 = new nissanoneToOneNnanetComCallcentre.GetPrimaryContactInfoResponse_element();
private static nissanoneToOneNnanetComCallcentre.Getassociated_dcno_id_element  obj21 = new nissanoneToOneNnanetComCallcentre.Getassociated_dcno_id_element();
private static nissanoneToOneNnanetComCallcentre.GetServiceHistory_element  obj22 = new nissanoneToOneNnanetComCallcentre.GetServiceHistory_element();
private static nissanoneToOneNnanetComCallcentre.GetSecurityTokenResponse_element   obj23 = new nissanoneToOneNnanetComCallcentre.GetSecurityTokenResponse_element();
private static nissanoneToOneNnanetComCallcentre.PingResponse_element  obj24 = new nissanoneToOneNnanetComCallcentre.PingResponse_element();
private static nissanoneToOneNnanetComCallcentre.GetAppointmentSubscribeURLResponse_element  obj25 = new nissanoneToOneNnanetComCallcentre.GetAppointmentSubscribeURLResponse_element();
private static nissanoneToOneNnanetComCallcentre.Getassociated_dcno_idResponse_element  obj26 = new nissanoneToOneNnanetComCallcentre.Getassociated_dcno_idResponse_element();
private static nissanoneToOneNnanetComCallcentre.GetServiceHistoryResponse_element   obj27 = new nissanoneToOneNnanetComCallcentre.GetServiceHistoryResponse_element();
private static nissanoneToOneNnanetComCallcentre.GetCommunicationHistoryResponse_element   obj28 = new nissanoneToOneNnanetComCallcentre.GetCommunicationHistoryResponse_element();
private static nissanoneToOneNnanetComCallcentre.GetDealerInfoResponse_element   obj29 = new nissanoneToOneNnanetComCallcentre.GetDealerInfoResponse_element();
private static nissanoneToOneNnanetComCallcentre.SearchDealerResponse_element   obj30 = new nissanoneToOneNnanetComCallcentre.SearchDealerResponse_element();
private static nissanoneToOneNnanetComCallcentre.CallResolutionResponse_element   obj31 = new nissanoneToOneNnanetComCallcentre.CallResolutionResponse_element();
private static nissanoneToOneNnanetComCallcentre.GetVersionResponse_element   obj32 = new nissanoneToOneNnanetComCallcentre.GetVersionResponse_element();

    static testmethod void testMethod1() {
    obj7.GetDealerInfo('234','adagag');
    }
    static testmethod void Method2(){
    obj7.CheckAppointmentTime ('hadaf','adagagdd');
    }
    static testmethod void Method3(){
    obj7.GetLog('adagagdd');
    }
    static testmethod void Method4(){
    obj7.GetServicesDue ('12552','adagagdd');
    }
    static testmethod void Method5(){
    obj7.GetPrimaryContactInfo (464661,'adagagdd');
    }
    static testmethod void Method6(){
    obj7.Ping();
    }
    static testmethod void Method7(){
    obj7.CheckAppointment('hadafaf','adagagddww');
    }
    static testmethod void Method8(){
    obj7.CallResolution('hadafafaa','adagagddwwee');
    }
    static testmethod void Method9(){
    obj7.GetServiceHistory(4546,'adagagdd');
    }
    static testmethod void Method10(){
    obj7.GetCommunicationHistory(125516512,'adagagdde');
    }
    static testmethod void Method11(){
    obj7.GetAssociatedCustomers(12455,'hi123');
    }
    static testmethod void Method12(){
    obj7.SearchDealer('hadafafaa@Wassdf','ahjahkda');
    }
    static testmethod void Method13(){
    obj7.GetVersion();
    }
    static testmethod void Method14(){
    obj7.SearchCustomer('hadafafaaasaWass','jlkajlaf');
    }
    static testmethod void Method15(){
    obj7.Getassociated_dcno_id(134662,'jlkajlaf');
    }
    static testmethod void Method16(){
    obj7.GetAppointmentSubscribeURL('134662',12455,54661,'hihiianinaif');
    }
    static testmethod void Method17(){
    obj7.GetSecurityToken('a@zen','12afa');
    }
    
    
}